#define DEFN 22
#define IF 15
#define LD_LOC_L 4
#define YIELD 19
#define DUP 10
#define LD_IMM 1
#define LD_IVAR 7
#define GOTO 14
#define LD_LOC 3
#define RETURN 18
#define LD_GVAR 9
#define REHANDLE 24
#define CALL 17
#define ST_LOC_L 6
#define RUN 21
#define SWAP 12
#define LD_SELF 2
#define ST_IVAR 8
#define DEFS 23
#define IF_NOT 16
#define ST_LOC 5
#define BREAK 20
#define ARY_SCATTER 13
#define POP 11
