#define YIELD 19
#define DUP 10
#define LD_IMM 1
#define ST_LOC_L 7
#define GOTO 14
#define ST_SELF 3
#define RETURN 18
#define ST_IVAR 9
#define REHANDLE 24
#define CALL 17
#define ST_LOC 6
#define DEFN 21
#define SWAP 12
#define LD_SELF 2
#define RAISE 23
#define IF_NOT 16
#define LD_LOC_L 5
#define BREAK 20
#define ARY_SCATTER 13
#define POP 11
#define LD_IVAR 8
#define DEFS 22
#define IF 15
#define LD_LOC 4
