#define ARY_SCATTER 17
#define BREAK 25
#define CALL 22
#define DEF_CVAR 9
#define DEFN 27
#define DEFS 28
#define DUP 14
#define GOTO 18
#define GOTO_E 19
#define HBODY_ENTER 31
#define IF 20
#define IF_NOT 21
#define JUMP_REHANDLE 30
#define LD_CVAR 10
#define LD_GVAR 12
#define LD_IMM 1
#define LD_IVAR 7
#define LD_LOC 3
#define LD_LOC_L 4
#define LD_SELF 2
#define MAKE_PROC 29
#define POP 15
#define RETURN 23
#define RUN 26
#define ST_CVAR 11
#define ST_GVAR 13
#define ST_IVAR 8
#define ST_LOC 5
#define ST_LOC_L 6
#define SWAP 16
#define YIELD 24
